### ISSUE TITLE
Přidat možnost "štítku" k epizodám na web

### ISSUE THREAD

**Issue by letajicitreska** [faktaoklimatu/web-2050podcast#118]
Možnost filtrovat epizody podle kategorií, poněvadž jich máme už docela dost. Kategorie by mohly být podobné, jako na webu - energetika, krajina, změna klimatu, doprava, průmysl, legislativa apod.

**Comment by mgrabovsky** [comment]
Pár vyjasňujících dotazů:

1. Na faktím webu teď máme [následujících šest okruhů](https://faktaoklimatu.cz/#temata):
    - klimatická změna;
    - emise skleníkových plynů;
    - energetika;
    - ekonomika;
    - mezinárodní dohody a legislativa a
    - krajina a ekosystémy.

    Chceš mít na podcastovém webu totožné?
2. Chceš jenom mít možnost filtrovat epizody podle štítků, nebo chceš i nějaké prolinkování na faktí web (např. odkaz na stránku tématu)?

**Comment by letajicitreska** [comment]
spíš takto:
- klimatická změna
- energeitika
- průmysl
- doprava
- ekonomika a finance
- politika a legislativa
- zemědělství a krajina
- společnost

asi by bylo fajn mít více štítků u jedné epizody. Třeba Max 2-3 ať to zas není šílené... 
Jinak tenhle seznam bych testoval a uvidíme jestli nám něco bude chybět..

**Comment by letajicitreska** [comment]
Čauky, našel se na toto nějaký čas? :)

**Comment by mgrabovsky** [comment]
Mám to rozdělané. Před pár týdny jsem na tom chvilku pracoval, rozplánoval si, co je potřeba udělat, ale ještě to pár hodin práce bude potřebovat.

Jsou dvě práce, které se dají dělat asynchronně: je třeba přiřadit štítky k existujícím epizodám a ke každému štítku napsat krátký popisek, který se pak ukáže na jeho stránce.

Jestli se ti chce, můžu udělat větev a můžeš zatím štítkovat.

**Comment by letajicitreska** [comment]
Pecka, jo to zní jako další typ práce který se dá dobře dělat v posteli s teplotou 😀

**Comment by mgrabovsky** [comment]
Udělal jsme větev [preview-stitky](https://github.com/faktaoklimatu/web-2050podcast/tree/preview-stitky).

* Seznam štítků a jejich popisky jsou v [`_data/tags.yml`](https://github.com/faktaoklimatu/web-2050podcast/blob/preview-stitky/_data/tags.yml).
* Štítky se přidávají podobně jako hosté – jenom do záhlaví přídáš položku `tags` se seznamem témat, viz můj [ukázkový commit](https://github.com/faktaoklimatu/web-2050podcast/commit/3bbdab1fc7010f39503bd2c7e10c8d8f5b9a21d0) (klidně přepiš).

**Comment by letajicitreska** [comment]
Koukám na to, zkusím napsat popisy štítků a přidat je k epizodám. 
Myslím, že by štítky měly být viditelné i v přehledu epizod nejen po rozkliknutí epizody. 
+ design štítků jsi ještě neřešil? Jestli je mít více barevní nebo jak..

**Comment by mgrabovsky** [comment]
Design jsem zatím vůbec neřešil. Zatím jsem to jen nahodil tak, aby šly někde vidět a aby se generovala stránka s epizodami k tématu.

**Comment by letajicitreska** [comment]
přišlo by mi praktické aby byly barvě oddělené, ale nevím jestli je to možné nějak citlivě zasadit do designu webu at to není hnusný

**Comment by letajicitreska** [comment]
Otagoval jsem všechny epizody, některý comity neprošly, nevím proč..

**Comment by mgrabovsky** [comment]
> přišlo by mi praktické aby byly barvě oddělené, ale nevím jestli je to možné nějak citlivě zasadit do designu webu at to není hnusný

Můžeme prodiskutovat s design týmem, až budou mít čas.

> Otagoval jsem všechny epizody, některý comity neprošly, nevím proč..

Došly nám kredity, řeším…
